
[CONFIG]
inizio_locale = 2025-11-15 13:00:00
fine_locale = 2025-11-15 15:00:00

# Il mio consiglio è lasciare 150, che è veloce ma non troppo
# Più grande è tempo_frame, più lentamente scorrono le immagini.
tempo_frame = 700

# Mette il nome della gif 
# esempio: nome_gif = che_bel_temporale avrete che_bel_temporale.gif in output
# Se mettete spazi nel nome questi verranno riempiti da _ (esempio: che bel temporale avrete che_bel_temporale.gif)
# Lasciate vuoto (nome_gif = ) per un nome che si basa su inizio_locale e fine_locale
nome_gif = 
